const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(s='')=>String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
let original=(window.AISON_NEWS||[]).map(x=>structuredClone(x));
let data=JSON.parse(localStorage.getItem('aison-admin-draft')||'null')||original.map(x=>structuredClone(x));
let selected=data[0]?.id;
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function save(){localStorage.setItem('aison-admin-draft',JSON.stringify(data));$('#adminStatus').textContent=`草稿已儲存在此瀏覽器 · ${data.length} 篇 · 最後修改 ${new Date().toLocaleTimeString('zh-HK')}`}
function renderList(){data.sort((a,b)=>(a.rank||99)-(b.rank||99));$('#adminList').innerHTML=data.map(n=>`<button class="admin-item ${n.id===selected?'active':''}" data-id="${esc(n.id)}"><span>${String(n.rank||0).padStart(2,'0')}</span><div><b>${esc(n.title)}</b><small>${esc(n.category||'未分類')} · ${n.verified?'✓ 已核實':'⚠ 未核實'}</small></div></button>`).join('');$$('.admin-item').forEach(b=>b.onclick=()=>{selected=b.dataset.id;render()})}
function field(label,key,type='text'){const n=data.find(x=>x.id===selected)||{};const value=n[key]??'';if(type==='textarea')return `<label class="admin-field"><span>${label}</span><textarea data-key="${key}" rows="4">${esc(Array.isArray(value)?value.join('\n'):value)}</textarea></label>`;if(type==='number')return `<label class="admin-field"><span>${label}</span><input data-key="${key}" type="number" value="${esc(value)}"></label>`;return `<label class="admin-field"><span>${label}</span><input data-key="${key}" value="${esc(Array.isArray(value)?value.join(', '):value)}"></label>`}
function renderEditor(){const n=data.find(x=>x.id===selected);if(!n){$('#adminEditor').innerHTML='<div class="empty" style="display:block">沒有文章。</div>';return}$('#adminEditor').innerHTML=`<div class="editor-head"><div><div class="mini-label">ARTICLE ${String(n.rank).padStart(2,'0')}</div><h2>${esc(n.title)}</h2></div><label class="verify-toggle"><input type="checkbox" id="verifiedToggle" ${n.verified?'checked':''}> 已核實</label></div><div class="editor-form">${field('排名','rank','number')}${field('ID / slug','id')}${field('標題','title')}${field('分類','category')}${field('標籤（逗號分隔）','tags')}${field('日期','date')}${field('閱讀時間','readTime')}${field('摘要','excerpt','textarea')}${field('30 秒睇明白','summary','textarea')}${field('發生咩事？','whatHappened','textarea')}${field('點解重要？','whyImportant','textarea')}${field('香港影響（每行一點）','hkImpact','textarea')}${field('AIson Take','take','textarea')}${field('來源名稱','sourceLabel')}${field('來源網址','sourceUrl')}</div><div class="editor-actions"><button class="primary-btn" id="saveArticle">儲存草稿</button><button class="ghost-btn" id="moveUp">↑ 提高排名</button><button class="ghost-btn" id="moveDown">↓ 降低排名</button></div>`;
$('#verifiedToggle').onchange=e=>{n.verified=e.target.checked;save();renderList()};$('#saveArticle').onclick=()=>{$$('[data-key]',$('#adminEditor')).forEach(el=>{let v=el.value.trim();if(el.dataset.key==='rank')v=Number(v)||99;if(el.dataset.key==='tags')v=v.split(',').map(x=>x.trim()).filter(Boolean);if(el.dataset.key==='hkImpact')v=v.split('\n').map(x=>x.trim()).filter(Boolean);n[el.dataset.key]=v});save();selected=n.id;render()};$('#moveUp').onclick=()=>move(-1);$('#moveDown').onclick=()=>move(1)}
function move(dir){data.sort((a,b)=>(a.rank||99)-(b.rank||99));const i=data.findIndex(x=>x.id===selected),j=i+dir;if(i<0||j<0||j>=data.length)return;[data[i].rank,data[j].rank]=[data[j].rank,data[i].rank];save();render()}
function render(){renderList();renderEditor();save()}
function download(){const blob=new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='news.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('已下載 news.json')}
$('#adminExport').onclick=download;$('#adminCopy').onclick=()=>navigator.clipboard.writeText(JSON.stringify(data,null,2)).then(()=>toast('已 Copy JSON'));$('#adminImport').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const incoming=JSON.parse(await f.text());if(!Array.isArray(incoming))throw Error();data=incoming;selected=data[0]?.id;save();render();toast('已匯入 JSON')}catch{toast('JSON 格式有問題')}};$('#adminReset').onclick=()=>{if(confirm('確定還原網站目前資料？未匯出的草稿會消失。')){data=original.map(x=>structuredClone(x));selected=data[0]?.id;save();render();toast('已還原')}};render();
