const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const NEWS=(window.AISON_NEWS||[]).slice().sort((a,b)=>(a.rank||99)-(b.rank||99));
const esc=(s='')=>String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const fmt=s=>{try{return new Intl.DateTimeFormat('zh-HK',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(s+'T00:00:00'))}catch{return s}};
const CATEGORY_VISUALS={
  'OpenAI':{icon:'◉',tone:'openai'},'Google':{icon:'G',tone:'google'},'Anthropic':{icon:'AI',tone:'anthropic'},
  'NVIDIA':{icon:'N',tone:'nvidia'},'Meta':{icon:'∞',tone:'meta'},'AI 安全':{icon:'⌁',tone:'safety'},
  'AI 晶片':{icon:'▦',tone:'chip'},'AI 政策':{icon:'⚖',tone:'policy'},'教育 AI':{icon:'✎',tone:'education'},
  'AI 工具':{icon:'✣',tone:'tools'}
};
function categoryVisual(category=''){return CATEGORY_VISUALS[category]||{icon:'✦',tone:'default'}}
function topItem(n){const v=categoryVisual(n.category);return '<a class="top-item" href="article.html?id='+encodeURIComponent(n.id)+'"><span class="num">'+String(n.rank).padStart(2,'0')+'</span><span class="top-symbol '+v.tone+'" aria-hidden="true">'+v.icon+'</span><span><b>'+esc(n.title)+'</b><small>'+esc(n.category)+'</small></span></a>'}
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function newsCard(n){const hay=(n.title+' '+n.excerpt+' '+n.category+' '+(n.tags||[]).join(' ')).toLowerCase(),v=categoryVisual(n.category),tags=(n.tags||[]).slice(0,3).map(t=>'<span class="tag">'+esc(t)+'</span>').join('');return '<a class="news-card" href="article.html?id='+encodeURIComponent(n.id)+'" data-hay="'+esc(hay)+'" data-cat="'+esc(n.category)+'"><div class="card-leading"><span class="rank">'+String(n.rank).padStart(2,'0')+'</span><span class="card-symbol '+v.tone+'" aria-hidden="true">'+v.icon+'</span></div><div><div class="card-overline"><span>'+esc(n.category)+'</span>'+(n.verified?'<b>✓ 已核實</b>':'')+'</div><h3>'+esc(n.title)+'</h3><p>'+esc(n.excerpt)+'</p><div class="meta">'+tags+(n.freshness?'<span class="freshness">'+esc(n.freshness)+'</span>':'')+'</div><div class="card-footer"><span>◷ '+fmt(n.date)+' · '+esc(n.readTime)+'</span><span class="card-arrow">→</span></div></div></a>'}
function setEdition(){const dates=NEWS.map(n=>n.date).filter(Boolean).sort();const latest=dates.at(-1);if($('#editionDate')&&latest)$('#editionDate').textContent=`${fmt(latest)} · 過去 24 小時優先 + 本週重要更新`;}
function renderHome(){const g=$('#newsGrid');if(!g)return;setEdition();g.innerHTML=NEWS.slice(0,10).map(newsCard).join('');$('#topList').innerHTML=NEWS.slice(0,3).map(topItem).join('');const cats=[...new Set(NEWS.map(n=>n.category))];$('#categoryList').innerHTML=['全部',...cats].map(c=>{const v=categoryVisual(c),count=c==='全部'?NEWS.length:NEWS.filter(n=>n.category===c).length;return '<button class="category-pill '+v.tone+'" data-cat="'+esc(c)+'"><i>'+(c==='全部'?'✦':v.icon)+'</i><span>'+esc(c)+'</span><b>'+count+'</b></button>'}).join('');bindFilters();bindSearch();}
function filterCards(cat='全部'){let shown=0;$$('.news-card').forEach(c=>{const ok=cat==='全部'||c.dataset.cat===cat;c.style.display=ok?'grid':'none';if(ok)shown++});if($('#empty'))$('#empty').style.display=shown?'none':'block';$$('.filter-btn').forEach(b=>b.classList.toggle('active',b.dataset.cat===cat));}
function bindFilters(){$$('.filter-btn,.category-pill').forEach(b=>b.addEventListener('click',()=>{filterCards(b.dataset.cat);document.querySelector('#today')?.scrollIntoView({behavior:'smooth',block:'start'})}))}
function searchResults(q=''){const term=q.trim().toLowerCase();const hits=!term?NEWS.slice(0,6):NEWS.filter(n=>(n.title+' '+n.excerpt+' '+n.category+' '+(n.tags||[]).join(' ')+' '+(n.take||'')).toLowerCase().includes(term));return hits.slice(0,12)}
function renderSearch(q=''){const root=$('#searchResults');if(!root)return;const hits=searchResults(q);root.innerHTML=hits.length?hits.map(n=>`<a class="search-result" href="article.html?id=${encodeURIComponent(n.id)}"><span class="num">${String(n.rank).padStart(2,'0')}</span><div><b>${esc(n.title)}</b><span>${esc(n.category)} · ${fmt(n.date)}</span></div></a>`).join(''):'<div class="empty" style="display:block">搵唔到相關內容。</div>'}
function bindSearch(){const modal=$('#searchModal'), input=$('#searchInput');if(!modal)return;const open=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');renderSearch('');setTimeout(()=>input?.focus(),50)};const close=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};$('#searchTrigger')?.addEventListener('click',open);$('#heroSearch')?.addEventListener('click',open);$('#closeSearch')?.addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});input?.addEventListener('input',()=>renderSearch(input.value));document.addEventListener('keydown',e=>{if(e.key==='Escape')close();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}})}
function renderArchive(){const grid=$('#archiveGrid');if(!grid)return;const sel=$('#archiveCategory'), input=$('#archiveSearch'), empty=$('#archiveEmpty'), stats=$('#archiveStats');const cats=[...new Set(NEWS.map(n=>n.category))].sort();sel.innerHTML='<option value="全部">全部分類</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');const render=()=>{const q=(input.value||'').trim().toLowerCase(), cat=sel.value;const hits=NEWS.filter(n=>(cat==='全部'||n.category===cat)&&(!q||(n.title+' '+n.excerpt+' '+n.category+' '+(n.tags||[]).join(' ')).toLowerCase().includes(q)));grid.innerHTML=hits.map(newsCard).join('');empty.style.display=hits.length?'none':'block';stats.textContent=`共 ${hits.length} 篇 · ${cats.length} 個分類 · 所有文章保留來源及日期`;};input.addEventListener('input',render);sel.addEventListener('change',render);render();bindSearch();}
function articleParagraph(text=''){return String(text).split(/\n+/).filter(Boolean).map(part=>`<p>${esc(part)}</p>`).join('')}
function storyContext(n){return n.reportingContext||`${n.summary||n.excerpt} 現時公開資料主要交代事件本身及其直接影響；在有更多官方細節前，應把已核實事實與市場推測分開理解。`}
function storyWatch(n){return n.whatToWatch||'接下來值得留意官方會否公布適用範圍、時間表及用戶安排。這些可以核實的細節，才會決定影響會否由單一公告延伸成實際的產品、成本或合規改變。'}
function renderArticle(){
 const id=new URLSearchParams(location.search).get('id')||NEWS[0]?.id,n=NEWS.find(x=>x.id===id)||NEWS[0];if(!n)return;
 document.title=`${n.title}｜AIson`;$('#crumbTitle').textContent=n.title;
 const visual=categoryVisual(n.category);
 $('#articleMeta').innerHTML=`<span class="article-category" data-category="${esc(n.category)}"><i>${visual.icon}</i>${esc(n.category)}</span><span>發布 ${fmt(n.date)}</span><span>·</span><span>${esc(n.readTime)}</span>${n.freshness?`<span class="freshness">${esc(n.freshness)}</span>`:''}${n.verified?'<span class="source-badge">✓ 已核實</span>':''}`;
 $('#articleTitle').textContent=n.title;$('#articleExcerpt').textContent=n.excerpt;$('#articleTags').innerHTML=(n.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('');$('#articleTopList').innerHTML=NEWS.slice(0,5).map(topItem).join('');
 const body=$('#articleBody');body.innerHTML=`<section class="report-opening"><div class="report-kicker">AIson DETAILED REPORT</div><h2>完整報導：事件核心與脈絡</h2>${articleParagraph(n.summary||n.excerpt)}<div class="report-note"><span>◎</span><p>本篇按已核實來源整理，並分開呈現已知事實、背景解讀、香港影響與值得跟進的細節。</p></div></section><section class="info-block"><h2>📰 目前已知：發生咩事？</h2>${articleParagraph(n.whatHappened||n.summary||n.excerpt)}</section><section class="info-block"><h2>🔎 事件背景與脈絡</h2>${articleParagraph(storyContext(n))}</section><section class="info-block"><h2>🎯 點解值得重視？</h2>${articleParagraph(n.whyImportant||'')}</section><section class="info-block"><h2>👀 接下來應該留意咩？</h2>${articleParagraph(storyWatch(n))}</section><section class="info-block"><div class="hkbox"><h2>🇭🇰 同香港人有咩關係？</h2><ul>${(n.hkImpact||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></section><section class="info-block"><div class="take"><img src="assets/mascot.webp" alt="AIson"><div><h2>🐶 AIson Take</h2>${articleParagraph(n.take||'')}</div></div></section><div class="source"><span>核實來源</span><a href="${esc(n.sourceUrl)}" target="_blank" rel="noopener noreferrer">${esc(n.sourceLabel||'官方來源')} ↗</a><span>· ${esc(n.sourceType||'來源')} · ${fmt(n.date)}</span></div>`;
 const related=NEWS.filter(x=>x.id!==n.id&&(x.category===n.category||(x.tags||[]).some(t=>(n.tags||[]).includes(t)))).slice(0,4);const wrap=document.createElement('div');wrap.className='related-wrap';wrap.innerHTML=`<div class="mini-label">KEEP READING</div><h2>相關新聞</h2><div class="related-grid">${(related.length?related:NEWS.filter(x=>x.id!==n.id).slice(0,4)).map(x=>`<a class="related-card" href="article.html?id=${encodeURIComponent(x.id)}"><b>${esc(x.title)}</b><span>${esc(x.category)} · ${fmt(x.date)}</span></a>`).join('')}</div>`;body.appendChild(wrap);
 const d=$('meta[name="description"]');if(d)d.content=n.excerpt;const ld={"@context":"https://schema.org","@type":"NewsArticle","headline":n.title,"datePublished":n.date,"dateModified":n.date,"description":n.excerpt,"mainEntityOfPage":location.href,"publisher":{"@type":"Organization","name":"AIson","logo":{"@type":"ImageObject","url":new URL('assets/icon-512.png',location.href).href}},"author":{"@type":"Organization","name":"AIson"}};if($('#jsonld'))$('#jsonld').textContent=JSON.stringify(ld)
}
async function shareArticle(){const title=$('#articleTitle')?.textContent||'AIson';if(navigator.share){try{await navigator.share({title,text:'AIson｜每日 AI 新聞・香港',url:location.href});return}catch{}}copyLink()}
function copyLink(){navigator.clipboard?.writeText(location.href).then(()=>toast('已複製文章連結')).catch(()=>toast('請手動複製網址'))}
function subscribe(e){if(location.protocol==='file:'){e.preventDefault();const input=e.target.querySelector('input[type=email]');if(!input?.value||!input.value.includes('@'))return toast('請輸入有效 Email');toast('預覽模式：正式部署 Netlify 後會提交訂閱');input.value='';return true}return true}
function decorateTopList(root){$$('.top-item',root).forEach((item,index)=>{const v=categoryVisual(NEWS[index]?.category||'');if(item.querySelector('.top-symbol'))return;const symbol=document.createElement('span'),b=item.querySelector('b'),anchor=b?.parentElement===item?b:(b?.parentElement||item.lastElementChild);symbol.className='top-symbol '+v.tone;symbol.textContent=v.icon;item.insertBefore(symbol,anchor);});}
function decorateArticle(){const category=$('#articleMeta .article-category')?.dataset.category||'';const v=categoryVisual(category),mark=$('#articleBrandMark');if(mark){mark.textContent=v.icon;mark.className='article-brand-mark '+v.tone;}$$('#articleBody .info-block h2').forEach(h=>h.classList.add('info-heading'));decorateTopList($('#articleTopList'));}
function decorateDaily(){$$('.daily-item').forEach((item,index)=>{const v=categoryVisual(NEWS[index]?.category||''),rank=$('.daily-rank',item);if(rank){rank.dataset.symbol=v.icon;rank.classList.add(v.tone);}});decorateTopList($('#dailyTop3'));}
function mobileMenu(){$('#menuBtn')?.addEventListener('click',()=>{const n=$('#mobileNav');n.style.display=n.style.display==='block'?'none':'block'})}
window.shareArticle=shareArticle;window.copyLink=copyLink;window.subscribe=subscribe;
function dailyThreadsText(){const date=NEWS.map(n=>n.date).filter(Boolean).sort().at(-1)||'';const lines=NEWS.slice(0,10).map(n=>`${String(n.rank).padStart(2,'0')}｜${n.title}\n${n.excerpt}`);return `🐶 AIson｜今日 AI 10 件事 ${fmt(date)}\n\n${lines.join('\\n\\n')}\n\n🇭🇰 每篇完整內容都有「同香港人有咩關係？」＋ AIson Take。`;}
function dailyHeadlinesText(){const date=NEWS.map(n=>n.date).filter(Boolean).sort().at(-1)||'';return `今日 AI 10 件事｜${fmt(date)}\n`+NEWS.slice(0,10).map(n=>`${String(n.rank).padStart(2,'0')} ${n.title}`).join('\\n');}
function renderDaily(){const list=$('#dailyList');if(!list)return;setEdition();const latest=NEWS.map(n=>n.date).filter(Boolean).sort().at(-1);if($('#dailyEdition')&&latest)$('#dailyEdition').textContent=`${fmt(latest)} · 每則均包括事件脈絡、重要性與香港影響`;list.innerHTML=NEWS.slice(0,10).map(n=>`<article class="daily-item"><div class="daily-rank">${String(n.rank).padStart(2,'0')}</div><div><div class="daily-meta"><span class="tag">${esc(n.category)}</span>${n.verified?'<span class="source-badge">✓ 已核實</span>':''}</div><h2><a href="article.html?id=${encodeURIComponent(n.id)}">${esc(n.title)}</a></h2><p class="daily-excerpt">${esc(n.excerpt)}</p><div class="daily-summary"><b>事件脈絡</b><span>${esc(n.summary||n.excerpt)}</span></div><div class="daily-why"><b>點解重要</b><span>${esc(n.whyImportant||'')}</span></div><div class="daily-take"><b>🐶 AIson Take</b><span>${esc(n.take||'')}</span></div><a class="text-link" href="article.html?id=${encodeURIComponent(n.id)}">睇完整報導與香港影響 →</a></div></article>`).join('');$('#dailyTop3').innerHTML=NEWS.slice(0,3).map(topItem).join('');$('#copyThreads')?.addEventListener('click',()=>navigator.clipboard.writeText(dailyThreadsText()).then(()=>toast('已 Copy Threads 版本')));$('#copyHeadlines')?.addEventListener('click',()=>navigator.clipboard.writeText(dailyHeadlinesText()).then(()=>toast('已 Copy 10 個標題')));bindSearch();}
document.addEventListener('DOMContentLoaded',()=>{mobileMenu();const p=document.body.dataset.page;if(p==='home')renderHome();if(p==='article'){renderArticle();decorateArticle()}if(p==='archive')renderArchive();if(p==='daily'){renderDaily();decorateDaily()}});
