const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const NEWS=(window.AISON_NEWS||[]).slice().sort((a,b)=>(a.rank||99)-(b.rank||99));
const STATUS=window.AISON_STATUS||{};
const SITE=window.AISON_SITE||{};
const SAVED_NEWS_KEY='aison-saved-news-v1';
const FOLLOWED_TOPICS_KEY='aison-followed-topics-v1';
const esc=(s='')=>String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const fmt=s=>{try{return new Intl.DateTimeFormat('zh-HK',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(s+'T00:00:00'))}catch{return s}};
function fmtBuildTime(value=''){try{const date=new Date(value);if(Number.isNaN(date.getTime()))throw new Error('invalid date');return new Intl.DateTimeFormat('zh-HK',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Hong_Kong',hour12:false}).format(date)+'（香港時間）'}catch{return '每日版本建置後更新'}}
const CATEGORY_VISUALS={
  'OpenAI':{icon:'◉',tone:'openai'},'Google':{icon:'G',tone:'google'},'Anthropic':{icon:'AI',tone:'anthropic'},
  'NVIDIA':{icon:'N',tone:'nvidia'},'Meta':{icon:'∞',tone:'meta'},'AI 安全':{icon:'⌁',tone:'safety'},
  'AI 晶片':{icon:'▦',tone:'chip'},'AI 政策':{icon:'⚖',tone:'policy'},'教育 AI':{icon:'✎',tone:'education'},
  'AI 工具':{icon:'✣',tone:'tools'}
};
function categoryVisual(category=''){return CATEGORY_VISUALS[category]||{icon:'✦',tone:'default'}}
function topItem(n){const v=categoryVisual(n.category);return '<a class="top-item" href="article.html?id='+encodeURIComponent(n.id)+'"><span class="num">'+String(n.rank).padStart(2,'0')+'</span><span class="top-symbol '+v.tone+'" aria-hidden="true">'+v.icon+'</span><span><b>'+esc(n.title)+'</b><small>'+esc(n.category)+'</small></span></a>'}
function briefText(text='',limit=88){const clean=String(text).replace(/\s+/g,' ').trim();return clean.length>limit?clean.slice(0,limit).replace(/[，。；、\s]+$/,'')+'…':clean}
function topBrief(n){const v=categoryVisual(n.category),why=briefText(n.whyImportant||n.summary||n.excerpt),hk=briefText((n.hkImpact||[])[0]||'了解這項改變對香港使用者的實際影響。',54);return '<a class="top-brief" href="article.html?id='+encodeURIComponent(n.id)+'"><div class="top-brief-head"><span class="num">'+String(n.rank).padStart(2,'0')+'</span><span class="top-symbol '+v.tone+'" aria-hidden="true">'+v.icon+'</span><span><b>'+esc(n.title)+'</b><small>'+esc(n.category)+' · 30 秒重點</small></span></div><p><strong>為何重要：</strong>'+esc(why)+'</p><span class="top-brief-hk">🇭🇰 '+esc(hk)+'</span><span class="top-brief-link">睇完整報導 →</span></a>'}
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function newsletterUrl(){return SITE.newsletter?.subscribeUrl||'https://yues-newsletter-c6d023.beehiiv.com/subscribe'}
function setupNewsletterLinks(){$$('[data-newsletter-link]').forEach(link=>link.setAttribute('href',newsletterUrl()))}
function savedIds(){try{const ids=JSON.parse(localStorage.getItem(SAVED_NEWS_KEY)||'[]');return Array.isArray(ids)?ids.filter(id=>typeof id==='string'):[]}catch{return []}}
function setSavedIds(ids){try{localStorage.setItem(SAVED_NEWS_KEY,JSON.stringify([...new Set(ids)]))}catch{toast('暫時未能儲存，請檢查瀏覽器設定')}}
function savedNews(){const ids=savedIds();return ids.map(id=>NEWS.find(n=>n.id===id)).filter(Boolean)}
function updateBookmarkButton(){const btn=$('#bookmarkBtn');if(!btn)return;const id=new URLSearchParams(location.search).get('id')||NEWS[0]?.id,active=savedIds().includes(id);btn.setAttribute('aria-pressed',String(active));btn.classList.toggle('saved',active);btn.innerHTML=active?'<span aria-hidden="true">★</span> 已加入稍後閱讀':'<span aria-hidden="true">☆</span> 加入稍後閱讀'}
function toggleBookmark(){const id=new URLSearchParams(location.search).get('id')||NEWS[0]?.id;if(!id)return;const ids=savedIds(),active=ids.includes(id);setSavedIds(active?ids.filter(x=>x!==id):[id,...ids]);updateBookmarkButton();renderSavedNews();toast(active?'已從稍後閱讀移除':'已加入稍後閱讀')}
function clearSavedNews(){setSavedIds([]);renderSavedNews();toast('已清除本機收藏')}
function renderSavedNews(){const root=$('#savedList');if(!root)return;const items=savedNews();root.innerHTML=items.length?items.slice(0,4).map(n=>'<a class="saved-item" href="article.html?id='+encodeURIComponent(n.id)+'"><span>★</span><b>'+esc(n.title)+'</b></a>').join(''):'<p class="saved-empty">未有收藏。文章頁按「加入稍後閱讀」，便可在此裝置保存。</p>';const count=$('#savedCount');if(count)count.textContent=items.length?String(items.length):'0';const clear=$('#clearSaved');if(clear)clear.hidden=!items.length}
function followedTopics(){try{const topics=JSON.parse(localStorage.getItem(FOLLOWED_TOPICS_KEY)||'[]');return Array.isArray(topics)?topics.filter(topic=>typeof topic==='string'):[]}catch{return []}}
function setFollowedTopics(topics){try{localStorage.setItem(FOLLOWED_TOPICS_KEY,JSON.stringify([...new Set(topics)]))}catch{toast('暫時未能儲存，請檢查瀏覽器設定')}}
function toggleFollowTopic(topic){const topics=followedTopics(),active=topics.includes(topic);setFollowedTopics(active?topics.filter(item=>item!==topic):[...topics,topic]);renderFollowing();toast(active?`已停止追蹤 ${topic}`:`已追蹤 ${topic}`)}
function renderFollowing(){const picker=$('#followTopicPicker'),feed=$('#followFeed'),summary=$('#followSummary');if(!picker||!feed||!summary)return;const categories=[...new Set(NEWS.map(n=>n.category))],topics=followedTopics().filter(topic=>categories.includes(topic)),matches=NEWS.filter(n=>topics.includes(n.category));picker.innerHTML=categories.map(category=>{const visual=categoryVisual(category),active=topics.includes(category);return '<button type="button" class="follow-topic '+visual.tone+(active?' active':'')+'" data-follow-topic="'+esc(category)+'" aria-pressed="'+active+'"><i>'+visual.icon+'</i><span>'+esc(category)+'</span><b>'+(!active?'＋':'✓')+'</b></button>'}).join('');summary.textContent=topics.length?`正在追蹤 ${topics.length} 個主題 · 有 ${matches.length} 則相關報導`:'揀選你關心的主題，之後每日更新會在這裡為你集中顯示。';feed.innerHTML=topics.length?(matches.slice(0,3).map(n=>{const visual=categoryVisual(n.category);return '<a class="follow-item" href="article.html?id='+encodeURIComponent(n.id)+'"><span class="top-symbol '+visual.tone+'">'+visual.icon+'</span><span><small>'+esc(n.category)+' · '+fmt(n.date)+'</small><b>'+esc(n.title)+'</b></span><i>→</i></a>'}).join('')||'<p class="follow-empty">暫時未有相符的新聞；下次更新時會自動配對。</p>'):'<p class="follow-empty">你的追蹤只儲存在目前瀏覽器，不需登入，也不會收集個人資料。</p>';$$('[data-follow-topic]',picker).forEach(button=>button.addEventListener('click',()=>toggleFollowTopic(button.dataset.followTopic)));}
function newsCard(n){const hay=(n.title+' '+n.excerpt+' '+n.category+' '+(n.tags||[]).join(' ')).toLowerCase(),v=categoryVisual(n.category),tags=(n.tags||[]).slice(0,3).map(t=>'<span class="tag">'+esc(t)+'</span>').join('');return '<a class="news-card" href="article.html?id='+encodeURIComponent(n.id)+'" data-hay="'+esc(hay)+'" data-cat="'+esc(n.category)+'"><div class="card-leading"><span class="rank">'+String(n.rank).padStart(2,'0')+'</span><span class="card-symbol '+v.tone+'" aria-hidden="true">'+v.icon+'</span></div><div><div class="card-overline"><span>'+esc(n.category)+'</span>'+(n.verified?'<b>✓ 已核實</b>':'')+'</div><h3>'+esc(n.title)+'</h3><p>'+esc(n.excerpt)+'</p><div class="meta">'+tags+(n.freshness?'<span class="freshness">'+esc(n.freshness)+'</span>':'')+'</div><div class="card-footer"><span>◷ '+fmt(n.date)+' · '+esc(n.readTime)+'</span><span class="card-arrow">→</span></div></div></a>'}
function editionDate(){const latest=NEWS.map(n=>n.date).filter(Boolean).sort().at(-1);return STATUS.editionDate||latest||''}
function setEdition(){const edition=editionDate();if($('#editionDate')&&edition)$('#editionDate').textContent=`${fmt(edition)} · 今日編輯版 · 過去 24 小時優先 + 本週重要更新`;}
function renderHome(){const g=$('#newsGrid');if(!g)return;setEdition();g.innerHTML=NEWS.slice(0,10).map(newsCard).join('');$('#topList').innerHTML=NEWS.slice(0,3).map(topBrief).join('');const cats=[...new Set(NEWS.map(n=>n.category))];$('#categoryList').innerHTML=['全部',...cats].map(c=>{const v=categoryVisual(c),count=c==='全部'?NEWS.length:NEWS.filter(n=>n.category===c).length;return '<button class="category-pill '+v.tone+'" data-cat="'+esc(c)+'"><i>'+(c==='全部'?'✦':v.icon)+'</i><span>'+esc(c)+'</span><b>'+count+'</b></button>'}).join('');bindFilters();bindSearch();renderSavedNews();renderFollowing();$('#clearSaved')?.addEventListener('click',clearSavedNews);}
function filterCards(cat='全部'){let shown=0;$$('.news-card').forEach(c=>{const ok=cat==='全部'||c.dataset.cat===cat;c.style.display=ok?'grid':'none';if(ok)shown++});if($('#empty'))$('#empty').style.display=shown?'none':'block';$$('.filter-btn').forEach(b=>b.classList.toggle('active',b.dataset.cat===cat));}
function bindFilters(){$$('.filter-btn,.category-pill').forEach(b=>b.addEventListener('click',()=>{filterCards(b.dataset.cat);document.querySelector('#today')?.scrollIntoView({behavior:'smooth',block:'start'})}))}
function searchResults(q=''){const term=q.trim().toLowerCase();const hits=!term?NEWS.slice(0,6):NEWS.filter(n=>(n.title+' '+n.excerpt+' '+n.category+' '+(n.tags||[]).join(' ')+' '+(n.take||'')).toLowerCase().includes(term));return hits.slice(0,12)}
function renderSearch(q=''){const root=$('#searchResults');if(!root)return;const hits=searchResults(q);root.innerHTML=hits.length?hits.map(n=>`<a class="search-result" href="article.html?id=${encodeURIComponent(n.id)}"><span class="num">${String(n.rank).padStart(2,'0')}</span><div><b>${esc(n.title)}</b><span>${esc(n.category)} · ${fmt(n.date)}</span></div></a>`).join(''):'<div class="empty" style="display:block">搵唔到相關內容。</div>'}
function bindSearch(){const modal=$('#searchModal'), input=$('#searchInput');if(!modal)return;const open=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');renderSearch('');setTimeout(()=>input?.focus(),50)};const close=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};$('#searchTrigger')?.addEventListener('click',open);$('#heroSearch')?.addEventListener('click',open);$('#closeSearch')?.addEventListener('click',close);modal.addEventListener('click',e=>{if(e.target===modal)close()});input?.addEventListener('input',()=>renderSearch(input.value));document.addEventListener('keydown',e=>{if(e.key==='Escape')close();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();open()}})}
function renderArchive(){const grid=$('#archiveGrid');if(!grid)return;const sel=$('#archiveCategory'), input=$('#archiveSearch'), empty=$('#archiveEmpty'), stats=$('#archiveStats');const cats=[...new Set(NEWS.map(n=>n.category))].sort();sel.innerHTML='<option value="全部">全部分類</option>'+cats.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');const render=()=>{const q=(input.value||'').trim().toLowerCase(), cat=sel.value;const hits=NEWS.filter(n=>(cat==='全部'||n.category===cat)&&(!q||(n.title+' '+n.excerpt+' '+n.category+' '+(n.tags||[]).join(' ')).toLowerCase().includes(q)));grid.innerHTML=hits.map(newsCard).join('');empty.style.display=hits.length?'none':'block';stats.textContent=`共 ${hits.length} 篇 · ${cats.length} 個分類 · 所有文章保留來源及日期`;};input.addEventListener('input',render);sel.addEventListener('change',render);render();bindSearch();}
function topicChoices(){const available=new Set(NEWS.flatMap(n=>[n.category,...(n.tags||[])]).filter(Boolean));const first=['OpenAI','ChatGPT','Google','Gemini','Anthropic','Claude','NVIDIA','Meta','AI Agent','AI 安全','AI 晶片','AI 政策','教育 AI','AI 工具'];const rest=[...available].filter(topic=>!first.includes(topic)).sort((a,b)=>a.localeCompare(b,'zh-Hant'));return [...first.filter(topic=>available.has(topic)),...rest].slice(0,24)}
function topicHits(topic){if(!topic||topic==='全部')return NEWS;const q=topic.toLowerCase();return NEWS.filter(n=>n.category===topic||(n.tags||[]).includes(topic)||n.title.toLowerCase().includes(q))}
function renderTopics(){const chips=$('#topicChips'),grid=$('#topicGrid'),heading=$('#topicHeading'),lead=$('#topicLead'),stats=$('#topicStats'),empty=$('#topicEmpty');if(!chips||!grid||!heading||!lead||!stats||!empty)return;const topics=['全部',...topicChoices()];let selected=new URLSearchParams(location.search).get('topic')||'全部';if(!topics.includes(selected))selected='全部';const render=()=>{const hits=topicHits(selected);heading.textContent=selected==='全部'?'所有主題':selected+' 追蹤';lead.textContent=selected==='全部'?'選擇一個公司、產品或分類，查看 AIson 已核實的相關報導。':`由最新到最早，整理 ${selected} 的公告、產品更新與香港影響。`;stats.textContent=`${hits.length} 篇已核實報導 · ${new Set(hits.map(n=>n.date)).size} 個更新日 · ${selected==='全部'?'所有分類':selected}`;chips.innerHTML=topics.map(topic=>`<button type="button" class="topic-chip${topic===selected?' active':''}" data-topic="${esc(topic)}" aria-pressed="${topic===selected}">${esc(topic)}</button>`).join('');grid.innerHTML=hits.map(newsCard).join('');empty.style.display=hits.length?'none':'block';$$('[data-topic]',chips).forEach(button=>button.addEventListener('click',()=>{selected=button.dataset.topic||'全部';const url=new URL(location.href);selected==='全部'?url.searchParams.delete('topic'):url.searchParams.set('topic',selected);history.replaceState({},'',url);render()}));};render();bindSearch();}
function articleParagraph(text=''){return String(text).split(/\n+/).filter(Boolean).map(part=>`<p>${esc(part)}</p>`).join('')}
function storyContext(n){return n.reportingContext||`${n.summary||n.excerpt} 現時公開資料主要交代事件本身及其直接影響；在有更多官方細節前，應把已核實事實與市場推測分開理解。`}
function storyWatch(n){return n.whatToWatch||'接下來值得留意官方會否公布適用範圍、時間表及用戶安排。這些可以核實的細節，才會決定影響會否由單一公告延伸成實際的產品、成本或合規改變。'}
function storyDeepDive(n){if(n.deepDive)return n.deepDive;const impacts=(n.hkImpact||[]).slice(0,2).join(' ');return `要讀懂這則消息，應把「公告已確認甚麼」和「仍待交付甚麼」分開。已確認部分來自本篇列出的原始來源；至於實際可用範圍、價格、效能、地區支援或最終商業效果，仍需等待後續產品文件、服務條款或獨立測試。\n\n對讀者而言，重點不只是跟上新聞標題，而是把它放回自己的工作流程、資料權限和成本結構中判斷。${impacts||'任何採用決定都應先以小規模、可覆核的測試驗證。'} 這亦是 AIson 會持續追蹤後續細節的原因。`}
function articleReadTime(n){const text=[n.summary,n.whatHappened,storyContext(n),storyDeepDive(n),n.whyImportant,storyWatch(n),n.take,...(n.hkImpact||[])].join('');return `${Math.max(3,Math.ceil(text.length/380))} 分鐘閱讀`}
function renderArticle(){
 const id=new URLSearchParams(location.search).get('id')||NEWS[0]?.id,n=NEWS.find(x=>x.id===id)||NEWS[0];if(!n)return;
 document.title=`${n.title}｜AIson`;$('#crumbTitle').textContent=n.title;
 const visual=categoryVisual(n.category);
 $('#articleMeta').innerHTML=`<span class="article-category" data-category="${esc(n.category)}"><i>${visual.icon}</i>${esc(n.category)}</span><span>發布 ${fmt(n.date)}</span><span>·</span><span>${esc(articleReadTime(n))}</span>${n.freshness?`<span class="freshness">${esc(n.freshness)}</span>`:''}${n.verified?'<span class="source-badge">✓ 已核實</span>':''}`;
 $('#articleTitle').textContent=n.title;$('#articleExcerpt').textContent=n.excerpt;$('#articleTags').innerHTML=(n.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('');$('#articleTopList').innerHTML=NEWS.slice(0,5).map(topItem).join('');
 const body=$('#articleBody');body.innerHTML=`<section class="report-opening"><div class="report-kicker">AIson DETAILED REPORT</div><h2>完整報導：事件核心與脈絡</h2>${articleParagraph(n.summary||n.excerpt)}<div class="report-note"><span>◎</span><p>本篇按已核實來源整理，並分開呈現已知事實、背景解讀、香港影響與值得跟進的細節。</p></div></section><section class="info-block"><h2>📰 目前已知：發生咩事？</h2>${articleParagraph(n.whatHappened||n.summary||n.excerpt)}</section><section class="info-block"><h2>🔎 事件背景與脈絡</h2>${articleParagraph(storyContext(n))}</section><section class="info-block deep-dive"><h2>🧭 深入解讀：由公告到實際影響</h2>${articleParagraph(storyDeepDive(n))}</section><section class="info-block"><h2>🎯 點解值得重視？</h2>${articleParagraph(n.whyImportant||'')}</section><section class="info-block"><h2>👀 接下來應該留意咩？</h2>${articleParagraph(storyWatch(n))}</section><section class="info-block"><div class="hkbox"><h2>🇭🇰 同香港人有咩關係？</h2><ul>${(n.hkImpact||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></section><section class="info-block"><div class="take"><img src="assets/mascot.webp" alt="AIson"><div><h2>🐶 AIson Take</h2>${articleParagraph(n.take||'')}</div></div></section><div class="source"><span>核實來源</span><a href="${esc(n.sourceUrl)}" target="_blank" rel="noopener noreferrer">${esc(n.sourceLabel||'官方來源')} ↗</a><span>· ${esc(n.sourceType||'來源')} · 文章日期 ${fmt(n.date)}</span><span class="source-updated">資料庫更新：${fmtBuildTime(STATUS.generatedAt||STATUS.lastBuild)}</span><a class="source-policy-link" href="methodology.html">編採方法與更正政策 →</a></div>`;
 const related=NEWS.filter(x=>x.id!==n.id).map(x=>{const shared=(x.tags||[]).filter(t=>(n.tags||[]).includes(t));return {...x,_sharedTags:shared,_score:(x.category===n.category?4:0)+shared.length*3};}).sort((a,b)=>b._score-a._score||String(b.date).localeCompare(String(a.date))).slice(0,4);const wrap=document.createElement('section');wrap.className='related-wrap';wrap.innerHTML=`<div class="mini-label">KEEP READING</div><h2>相關新聞</h2><p class="related-intro">按同一分類及共同標籤配對，方便你由一則新聞追到完整脈絡。</p><div class="related-grid">${related.map(x=>{const reason=x._sharedTags.length?'共同標籤：'+x._sharedTags.slice(0,2).join('、'):x.category===n.category?'同一分類：'+x.category:'延伸閱讀';return `<a class="related-card" href="article.html?id=${encodeURIComponent(x.id)}"><span class="related-reason">${esc(reason)}</span><b>${esc(x.title)}</b><span>${fmt(x.date)} · ${esc(x.readTime)}</span></a>`}).join('')}</div>`;body.appendChild(wrap);renderArticleNavigation();updateBookmarkButton();
 const d=$('meta[name="description"]');if(d)d.content=n.excerpt;const ld={"@context":"https://schema.org","@type":"NewsArticle","headline":n.title,"datePublished":n.date,"dateModified":n.date,"description":n.excerpt,"mainEntityOfPage":location.href,"publisher":{"@type":"Organization","name":"AIson","logo":{"@type":"ImageObject","url":new URL('assets/icon-512.png',location.href).href}},"author":{"@type":"Organization","name":"AIson"}};if($('#jsonld'))$('#jsonld').textContent=JSON.stringify(ld)
}
function renderArticleNavigation(){const body=$('#articleBody'),toc=$('#articleToc'),progress=$('#articleProgress');if(!body)return;const headings=[...body.querySelectorAll('.report-opening h2,.info-block h2')];headings.forEach((heading,index)=>heading.id=`article-section-${index+1}`);if(toc){toc.innerHTML=`<div class="panel-kicker">ARTICLE GUIDE</div><h3>本篇重點</h3><ol>${headings.map(heading=>`<li><a href="#${heading.id}">${esc(heading.textContent.replace(/^\S+\s*/,''))}</a></li>`).join('')}</ol>`;}if(!progress)return;const update=()=>{const start=body.offsetTop-110,end=body.offsetTop+body.offsetHeight-innerHeight,ratio=Math.max(0,Math.min(1,(scrollY-start)/Math.max(1,end-start)));progress.firstElementChild.style.transform=`scaleX(${ratio})`;};window.addEventListener('scroll',update,{passive:true});update();}
async function shareArticle(){const title=$('#articleTitle')?.textContent||'AIson';if(navigator.share){try{await navigator.share({title,text:'AIson｜每日 AI 新聞・香港',url:location.href});return}catch{}}copyLink()}
function copyLink(){navigator.clipboard?.writeText(location.href).then(()=>toast('已複製文章連結')).catch(()=>toast('請手動複製網址'))}
function subscribe(e){if(location.protocol==='file:'){e.preventDefault();const input=e.target.querySelector('input[type=email]');if(!input?.value||!input.value.includes('@'))return toast('請輸入有效 Email');toast('預覽模式：正式部署 Netlify 後會提交訂閱');input.value='';return true}return true}
function decorateTopList(root){$$('.top-item',root).forEach((item,index)=>{const v=categoryVisual(NEWS[index]?.category||'');if(item.querySelector('.top-symbol'))return;const symbol=document.createElement('span'),b=item.querySelector('b'),anchor=b?.parentElement===item?b:(b?.parentElement||item.lastElementChild);symbol.className='top-symbol '+v.tone;symbol.textContent=v.icon;item.insertBefore(symbol,anchor);});}
function decorateArticle(){const category=$('#articleMeta .article-category')?.dataset.category||'';const v=categoryVisual(category),mark=$('#articleBrandMark');if(mark){mark.textContent=v.icon;mark.className='article-brand-mark '+v.tone;}$$('#articleBody .info-block h2').forEach(h=>h.classList.add('info-heading'));decorateTopList($('#articleTopList'));}
function decorateDaily(){$$('.daily-item').forEach((item,index)=>{const v=categoryVisual(NEWS[index]?.category||''),rank=$('.daily-rank',item);if(rank){rank.dataset.symbol=v.icon;rank.classList.add(v.tone);}});decorateTopList($('#dailyTop3'));}
function mobileMenu(){$('#menuBtn')?.addEventListener('click',()=>{const n=$('#mobileNav');n.style.display=n.style.display==='block'?'none':'block'})}
window.shareArticle=shareArticle;window.copyLink=copyLink;window.subscribe=subscribe;window.toggleBookmark=toggleBookmark;
function dailyThreadsText(){const date=editionDate();const lines=NEWS.slice(0,10).map(n=>`${String(n.rank).padStart(2,'0')}｜${n.title}\n${n.excerpt}`);return `🐶 AIson｜今日 AI 10 件事 ${fmt(date)}\n\n${lines.join('\\n\\n')}\n\n🇭🇰 每篇完整內容都有「同香港人有咩關係？」＋ AIson Take。`;}
function dailyHeadlinesText(){const date=editionDate();return `今日 AI 10 件事｜${fmt(date)}\n`+NEWS.slice(0,10).map(n=>`${String(n.rank).padStart(2,'0')} ${n.title}`).join('\\n');}
function renderDaily(){const list=$('#dailyList');if(!list)return;setEdition();const edition=editionDate();if($('#dailyEdition')&&edition)$('#dailyEdition').textContent=`${fmt(edition)} · 每則均包括事件脈絡、重要性與香港影響`;list.innerHTML=NEWS.slice(0,10).map(n=>`<article class="daily-item"><div class="daily-rank">${String(n.rank).padStart(2,'0')}</div><div><div class="daily-meta"><span class="tag">${esc(n.category)}</span>${n.verified?'<span class="source-badge">✓ 已核實</span>':''}</div><h2><a href="article.html?id=${encodeURIComponent(n.id)}">${esc(n.title)}</a></h2><p class="daily-excerpt">${esc(n.excerpt)}</p><div class="daily-summary"><b>事件脈絡</b><span>${esc(n.summary||n.excerpt)}</span></div><div class="daily-why"><b>點解重要</b><span>${esc(n.whyImportant||'')}</span></div><div class="daily-take"><b>🐶 AIson Take</b><span>${esc(n.take||'')}</span></div><a class="text-link" href="article.html?id=${encodeURIComponent(n.id)}">睇完整報導與香港影響 →</a></div></article>`).join('');$('#dailyTop3').innerHTML=NEWS.slice(0,3).map(topItem).join('');$('#copyThreads')?.addEventListener('click',()=>navigator.clipboard.writeText(dailyThreadsText()).then(()=>toast('已 Copy Threads 版本')));$('#copyHeadlines')?.addEventListener('click',()=>navigator.clipboard.writeText(dailyHeadlinesText()).then(()=>toast('已 Copy 10 個標題')));bindSearch();}
function weeklyStories(){const end=editionDate();if(!end)return[];const startDate=new Date(`${end}T12:00:00Z`);startDate.setUTCDate(startDate.getUTCDate()-6);const start=startDate.toISOString().slice(0,10);return NEWS.filter(n=>n.date>=start&&n.date<=end).sort((a,b)=>String(b.date).localeCompare(String(a.date))||(a.rank||99)-(b.rank||99));}
function renderWeekly(){const list=$('#weeklyList');if(!list)return;const stories=weeklyStories(),end=editionDate();if(!stories.length)return;const startDate=new Date(`${end}T12:00:00Z`);startDate.setUTCDate(startDate.getUTCDate()-6);const start=startDate.toISOString().slice(0,10),cats=[...new Set(stories.map(n=>n.category))],verified=stories.filter(n=>n.verified).length,top=stories.slice().sort((a,b)=>(a.rank||99)-(b.rank||99)).slice(0,3);$('#weeklyEdition').textContent=`${fmt(start)} 至 ${fmt(end)} · ${stories.length} 則已核實新聞`;$('#weeklyStats').innerHTML=`<span><b>${stories.length}</b>則本週報導</span><span><b>${cats.length}</b>個主題分類</span><span><b>${verified}</b>則已核實來源</span>`;$('#weeklyFocus').innerHTML=top.map((n,i)=>{const v=categoryVisual(n.category);return `<a class="weekly-focus" href="article.html?id=${encodeURIComponent(n.id)}"><span class="weekly-number">0${i+1}</span><span class="top-symbol ${v.tone}">${v.icon}</span><div><small>${esc(n.category)}</small><h2>${esc(n.title)}</h2><p>${esc(briefText(n.whyImportant||n.summary||n.excerpt,110))}</p><span>睇完整分析 →</span></div></a>`}).join('');const groups=cats.map(category=>({category,items:stories.filter(n=>n.category===category)})).sort((a,b)=>b.items.length-a.items.length).slice(0,4);$('#weeklyThemes').innerHTML=groups.map(group=>`<article class="weekly-theme"><div><span>${esc(group.category)}</span><b>${group.items.length} 則</b></div><h3>${esc(group.items[0].title)}</h3><p>${esc(briefText(group.items[0].whyImportant||group.items[0].excerpt,100))}</p><a href="article.html?id=${encodeURIComponent(group.items[0].id)}">閱讀焦點 →</a></article>`).join('');list.innerHTML=stories.map(n=>`<a class="weekly-item" href="article.html?id=${encodeURIComponent(n.id)}"><span>${fmt(n.date)}</span><b>${esc(n.title)}</b><small>${esc(n.category)} · ${esc(n.readTime)}</small></a>`).join('');bindSearch();}
document.addEventListener('DOMContentLoaded',()=>{mobileMenu();setupNewsletterLinks();const p=document.body.dataset.page;if(p==='home')renderHome();if(p==='article'){renderArticle();decorateArticle()}if(p==='archive')renderArchive();if(p==='topics')renderTopics();if(p==='daily'){renderDaily();decorateDaily()}if(p==='weekly')renderWeekly();if(p==='guides')bindSearch();});
