#!/usr/bin/env python3
"""Send today's AIson newsletter as a Brevo email campaign.

This script consumes the RSS generated by tools/build_newsletter.py. It is safe
by default: no network request is made in --dry-run mode, and stale editions
are rejected before contacting Brevo.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

CONTENT_NS = "{http://purl.org/rss/1.0/modules/content/}"
BREVO_API = "https://api.brevo.com/v3"
TIMEZONE = ZoneInfo("Asia/Hong_Kong")


def latest_edition(feed_path: Path) -> tuple[str, str, str]:
    root = ET.parse(feed_path).getroot()
    channel = root.find("channel")
    item = channel.find("item") if channel is not None else None
    if item is None:
        raise ValueError("newsletter feed has no edition")

    title = item.findtext("title", default="")
    match = re.search(r"(\d{4}-\d{2}-\d{2})$", title)
    if not match:
        raise ValueError("latest newsletter title does not end with an ISO date")

    date = match.group(1)
    datetime.strptime(date, "%Y-%m-%d")
    content = item.findtext(CONTENT_NS + "encoded", default="")
    if len(re.findall(r"<h2\b", content, flags=re.IGNORECASE)) != 10:
        raise ValueError("latest newsletter must contain exactly 10 story headings")
    return date, title, content


def request_brevo(method: str, path: str, payload: dict | None = None):
    api_key = os.environ.get("BREVO_API_KEY", "").strip()
    if not api_key:
        raise RuntimeError("BREVO_API_KEY secret is missing")

    body = None if payload is None else json.dumps(payload, ensure_ascii=False).encode("utf-8")
    request = urllib.request.Request(
        BREVO_API + path,
        data=body,
        method=method,
        headers={
            "api-key": api_key,
            "accept": "application/json",
            "content-type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            response_body = response.read()
            if not response_body:
                return {}
            return json.loads(response_body.decode("utf-8"))
    except urllib.error.HTTPError as exc:
        # Do not include request headers or credentials in logs.
        detail = exc.read().decode("utf-8", errors="replace")[:1000]
        raise RuntimeError(f"Brevo API returned HTTP {exc.code}: {detail}") from None
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Brevo API request failed: {exc.reason}") from None


def campaigns():
    query = urllib.parse.urlencode({"type": "classic", "limit": 100, "offset": 0, "sort": "desc"})
    result = request_brevo("GET", "/emailCampaigns?" + query)
    return result.get("campaigns", [])


def send_campaign(campaign_id: int):
    request_brevo("POST", f"/emailCampaigns/{campaign_id}/sendNow", {})


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--feed", type=Path, default=Path("newsletter.xml"))
    parser.add_argument("--dry-run", action="store_true", help="validate and preview without calling Brevo")
    args = parser.parse_args()

    try:
        edition_date, title, content = latest_edition(args.feed)
        today_hkt = datetime.now(TIMEZONE).date().isoformat()
        if edition_date != today_hkt:
            print(f"SKIP: latest edition is {edition_date}; Hong Kong date is {today_hkt}")
            return 0

        campaign_name = f"AIson Daily {edition_date}"
        html_content = (
            content
            + '<hr><p style="color:#64748b;font-size:12px;line-height:1.6">'
            + "你收到此郵件，因為你曾訂閱 AIson 每日新聞。"
            + '如不想再收到，請<a href="{{ unsubscribe }}">取消訂閱</a>。'
            + "</p>"
        )

        if args.dry_run:
            print(f"DRY RUN: {campaign_name}")
            print(f"Subject: {title}")
            print(f"HTML bytes: {len(html_content.encode('utf-8'))}")
            print("Brevo was not contacted; no email was sent.")
            return 0

        list_id = os.environ.get("BREVO_LIST_ID", "").strip()
        sender_email = os.environ.get("BREVO_SENDER_EMAIL", "").strip()
        sender_name = os.environ.get("BREVO_SENDER_NAME", "AIson").strip() or "AIson"
        if not list_id.isdigit():
            raise RuntimeError("BREVO_LIST_ID must be set to the numeric ID of the opted-in newsletter list")
        if not sender_email:
            raise RuntimeError("BREVO_SENDER_EMAIL must be set to a verified Brevo sender address")

        campaign_payload = {
            "name": campaign_name,
            "subject": title,
            "previewText": "每日幫香港人篩選全球最值得知道的 AI 大事。",
            "sender": {"name": sender_name, "email": sender_email},
            "recipients": {"listIds": [int(list_id)]},
            "htmlContent": html_content,
            "tag": "aison-daily-newsletter",
        }
        existing = next((item for item in campaigns() if item.get("name") == campaign_name), None)
        if existing:
            campaign_id = int(existing["id"])
            detail = request_brevo("GET", f"/emailCampaigns/{campaign_id}")
            status = str(detail.get("status", "")).lower()
            if status != "draft":
                print(f"SKIP: {campaign_name} already exists with status {status or 'unknown'}")
                return 0
            # Refresh an interrupted draft with the current edition before sending it.
            request_brevo("PUT", f"/emailCampaigns/{campaign_id}", campaign_payload)
        else:
            created = request_brevo("POST", "/emailCampaigns", campaign_payload)
            campaign_id = int(created["id"])

        send_campaign(campaign_id)
        print(f"Sent Brevo campaign {campaign_id} for edition {edition_date}")
        return 0
    except (OSError, ValueError, RuntimeError, KeyError, TypeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
